name: ci-workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome step
        run: echo "Welcome to this repo"
      - name: Checkout
        uses: actions/checkout@V4
      - name: check commits
        uses: sultansoy/pr-commits-count@v1.0